/* ============================================
   ViewYourSite - Export System
   Export to clean standalone HTML/CSS/JS
   ============================================ */

const Export = {
    init() {
        this.setupExportModal();
        return this;
    },
    
    setupExportModal() {
        const exportBtn = document.getElementById('exportBtn');
        const modal = document.getElementById('exportModal');
        const closeBtn = document.getElementById('closeExport');
        const downloadBtn = document.getElementById('downloadExport');
        
        exportBtn?.addEventListener('click', () => {
            modal.classList.add('visible');
        });
        
        closeBtn?.addEventListener('click', () => {
            modal.classList.remove('visible');
        });
        
        downloadBtn?.addEventListener('click', () => {
            const type = document.querySelector('input[name="exportType"]:checked')?.value || 'html';
            const minify = document.getElementById('minifyExport')?.checked || false;
            const inlineImages = document.getElementById('inlineImages')?.checked || false;
            
            if (type === 'html') {
                this.downloadHTML(minify, inlineImages);
            } else {
                this.downloadZIP(minify, inlineImages);
            }
            
            modal.classList.remove('visible');
        });
        
        // Close on overlay click
        modal?.addEventListener('click', (e) => {
            if (e.target === modal) {
                modal.classList.remove('visible');
            }
        });
    },
    
    generateHTML(options = {}) {
        AppState.saveCurrentPageElements();
        
        const { minify = false, inlineImages = false } = options;
        const project = AppState.project;
        const pages = AppState.pages;
        
        // Generate CSS from elements
        let css = this.generateCSS(pages);
        if (minify) css = this.minifyCSS(css);
        
        // Generate HTML for each page
        const pageHTMLs = pages.map(page => {
            return this.generatePageHTML(page, inlineImages);
        });
        
        // Main index page (first page)
        const mainHTML = pageHTMLs[0] || '';
        
        // Full document
        const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${pages[0]?.settings?.title || project.name || 'My Website'}</title>
    ${pages[0]?.settings?.description ? `<meta name="description" content="${pages[0].settings.description}">` : ''}
    <style>
/* Generated by ViewYourSite */
${css}
${pages[0]?.settings?.customCSS || ''}
    </style>
</head>
<body>
${mainHTML}
${pages[0]?.settings?.customJS ? `<script>\n${pages[0].settings.customJS}\n</script>` : ''}
</body>
</html>`;
        
        return html;
    },
    
    generatePageHTML(page, inlineImages) {
        const elements = page.elements || [];
        
        const elementsHTML = elements.map(el => this.elementToHTML(el, inlineImages)).join('\n');
        
        return elementsHTML;
    },
    
    elementToHTML(element, inlineImages) {
        const styles = element.styles || {};
        const props = element.properties || {};
        const content = element.content || '';
        
        // Build style string
        const styleString = Object.entries(styles)
            .filter(([key, value]) => value && value !== '' && value !== 'auto' && value !== 'none')
            .map(([key, value]) => `${this.camelToKebab(key)}: ${value}`)
            .join('; ');
        
        // Handle different element types
        switch (element.type) {
            case 'heading':
                return `<h1 style="${styleString}">${content}</h1>`;
            
            case 'subheading':
                return `<h2 style="${styleString}">${content}</h2>`;
            
            case 'paragraph':
                return `<p style="${styleString}">${content}</p>`;
            
            case 'text':
            case 'span':
                return `<span style="${styleString}">${content}</span>`;
            
            case 'link':
                return `<a href="${props.href || '#'}" target="${props.target || '_self'}" style="${styleString}">${content}</a>`;
            
            case 'image':
                if (props.src && inlineImages && props.src.startsWith('data:')) {
                    return `<img src="${props.src}" alt="${props.alt || ''}" style="${styleString}">`;
                } else if (props.src) {
                    return `<img src="${props.src}" alt="${props.alt || ''}" style="${styleString}" loading="lazy">`;
                } else {
                    return `<div style="${styleString};display:flex;align-items:center;justify-content:center;background:#f0f0f0;color:#888;">Image Placeholder</div>`;
                }
            
            case 'video':
                return `<video src="${props.src || ''}" ${props.controls ? 'controls' : ''} ${props.autoplay ? 'autoplay' : ''} ${props.loop ? 'loop' : ''} ${props.muted ? 'muted' : ''} style="${styleString}" poster="${props.poster || ''}"></video>`;
            
            case 'button':
            case 'buttonOutline':
                return `<button type="button" style="${styleString}">${content}</button>`;
            
            case 'input':
                return `<input type="text" placeholder="Enter text..." style="${styleString}">`;
            
            case 'textarea':
                return `<textarea placeholder="Enter message..." rows="4" style="${styleString}"></textarea>`;
            
            case 'select':
                return `<select style="${styleString}"><option>Option 1</option><option>Option 2</option><option>Option 3</option></select>`;
            
            case 'container':
            case 'section':
                return `<div style="${styleString}">${content}</div>`;
            
            case 'divider':
                return `<hr style="${styleString}">`;
            
            case 'spacer':
                return `<div style="${styleString}"></div>`;
            
            default:
                // For complex components with HTML content
                if (content.includes('<')) {
                    return `<div style="${styleString}">${content}</div>`;
                }
                return `<div style="${styleString}">${content}</div>`;
        }
    },
    
    generateCSS(pages) {
        let css = `
/* Base Styles */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    line-height: 1.6;
    color: #333;
    background: #fff;
}

img {
    max-width: 100%;
    height: auto;
}

/* Responsive */
@media (max-width: 768px) {
    body {
        padding: 10px;
    }
}
`;
        return css;
    },
    
    camelToKebab(str) {
        return str.replace(/([A-Z])/g, '-$1').toLowerCase();
    },
    
    minifyCSS(css) {
        return css
            .replace(/\/\*[\s\S]*?\*\//g, '') // Remove comments
            .replace(/\s+/g, ' ')              // Collapse whitespace
            .replace(/\s*([{};:,])\s*/g, '$1')  // Remove spaces around symbols
            .replace(/;}/g, '}');               // Remove last semicolon
    },
    
    downloadHTML(minify, inlineImages) {
        const html = this.generateHTML({ minify, inlineImages });
        this.downloadFile(html, 'website.html', 'text/html');
        Toast.show('HTML exported successfully!', 'success');
    },
    
    downloadZIP(minify, inlineImages) {
        // For ZIP, we'll create a simple multi-file structure as text
        AppState.saveCurrentPageElements();
        
        const project = AppState.project;
        const pages = AppState.pages;
        
        let output = `// ViewYourSite Export - ${new Date().toISOString()}
// Project: ${project.name}
// Pages: ${pages.length}
// Elements: ${pages.reduce((sum, p) => sum + (p.elements?.length || 0), 0)}

=====================================
= INDEX.HTML =
=====================================

${this.generateHTML({ minify, inlineImages })}

`;

        // Add additional pages
        if (pages.length > 1) {
            pages.slice(1).forEach((page, i) => {
                output += `

=====================================
= ${page.name.replace(/\s+/g, '_').toUpperCase()}.HTML =
=====================================

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${page.settings.title || page.name}</title>
</head>
<body>
${this.generatePageHTML(page, inlineImages)}
</body>
</html>

`;
            });
        }

        this.downloadFile(output, 'website-export.txt', 'text/plain');
        Toast.show('Export data ready! (Convert to ZIP manually)', 'success');
    },
    
    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    },
    
    copyToClipboard(text) {
        navigator.clipboard.writeText(text).then(() => {
            Toast.show('Copied to clipboard!', 'success');
        }).catch(() => {
            Toast.show('Failed to copy', 'error');
        });
    }
};

// Make globally available
window.Export = Export;
